---
- name: Install vim and configure settings
  hosts: all
  become: true
  tasks:
    - name: Install vim on Debian
      # apt:
      ansible.builtin.apt:
        name: vim
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Deploy .vimrc to user home
      template:
        src: vimrc.j2
        dest: "/home/acala/.vimrc"
        owner: "acala"
        group: "acala"
        mode: "0644"
      when: ansible_facts['os_family'] == "Debian"

    - name: Install vim on RedHat/Amazon Linux
      # yum:
      ansible.builtin.dnf:
        name: vim
        state: present
      when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Amazon"

    - name: Deploy .vimrc to user home
      template:
        src: vimrc.j2
        dest: "/home/ec2-user/.vimrc"
        owner: "ec2-user"
        group: "ec2-user"
        mode: "0644"
      when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Amazon"
