---
- name: upgrade all packages
  hosts: all
  become: true
  tasks:
  - name: update packages
    ansible.builtin.dnf:
      name:
        - '*'
      state: latest
    when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Amazon"

  - name: apt-get dist-upgrade
    ansible.builtin.apt:
      update_cache: true
      upgrade: dist
      lock_timeout: 300 
    when: ansible_facts['os_family'] == "Debian"